##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## X|Y|Z & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: ___generators
description: This project contains a set of generators to help speed up development.
publish_to: none

## -----------------------------------------------------------------------------

environment:

  sdk: ^3.0.0

## -----------------------------------------------------------------------------

dependencies:

   xyz_gen:
    git: 
      url: https://github.com/robmllze/xyz_gen.git
   xyz_utils:
    git: 
      url: https://github.com/robmllze/xyz_utils.git

dependency_overrides:

  xyz_gen: ^0.55.0
  xyz_utils: ^0.51.0

## -----------------------------------------------------------------------------

dev_dependencies:

  lints: ^3.0.0